config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'admin/dashboard#index'

  namespace :admin do
    get '/dashboard', to: 'dashboard#index', as: '/'
    get '/dashboard/:id', to: 'dashboard#show', as: :climbing_route
    get '/dashboard/:id/edit', to: 'dashboard#edit', as: :edit_climbing_route
    patch '/dashboard/:id', to: 'dashboard#update', as: :update_climbing_route
  end

  namespace :api do
    namespace :v1 do
      post '/all-routes-per-sector', to: 'climbing_routes#all_routes_per_sector', as: :all_routes_per_sector
      post '/training-routes-recommendations', to: 'climbing_routes#training_routes_recommendations', as: :training_routes_recommendations
    end
  end
end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < ApplicationController
  before_action :find_climbing_route, only: [ :show, :edit, :update ]

  def index
    @climbing_routes = ClimbingRoute.all
  end

  def show
  end

  def edit
    @styles = ClimbingRoute.styles.keys
    @angles = ClimbingRoute.angles.keys
  end

  def update
    if @climbing_route.update(route_params)
      redirect_to admin_climbing_route_path(@climbing_route)
    else
      render :edit
    end
  end

  private

  def find_climbing_route
    @climbing_route = ClimbingRoute.find(params[:id])
  end

  def route_params
    params.require(:climbing_route).permit(:name, :grade, :style, :stars, :height, :angle)
  end
end

app/views/admin/dashboard/edit.html.erb
<div class="container">
  <h1>Edit <%= @climbing_route.name %></h1>
  <h3>Crag: <%= @climbing_route.crag.name %></h3>
  <p>Standardized grade: <%= @climbing_route.standardized_grade %></p>

  <%= simple_form_for(@climbing_route, url: admin_update_climbing_route_path(@climbing_route)) do |f| %>
    <%= f.input :name %>
    <%= f.input :grade %>
    <%= f.input :style, as: :select, collection: @styles, include_blank: false %>
    <%= f.input :stars %>
    <%= f.input :height %>
    <%= f.input :angle, as: :select, collection: @angles, include_blank: false  %>

    <%= f.submit %>
  <% end %>
  <%= link_to 'Dashboard', admin_path %>
  <%= link_to @climbing_route.name, admin_climbing_route_path(@climbing_route) %>
</div>

app/views/admin/dashboard/index.html.erb
<div class="container">
  <h1>Dashboard</h1>

  <ul>
    <% @climbing_routes.each do |climbing_route| %>
      <li><%= climbing_route.id %> <%= link_to climbing_route.name, admin_climbing_route_path(climbing_route) %></li>
      <li><%= link_to 'Edit', admin_edit_climbing_route_path(climbing_route) %></li>
    <% end %>
  </ul>
</div>

app/views/admin/dashboard/show.html.erb
<div class="container">
  <h1><%= @climbing_route.name %></h1>
  <h3>Crag: <%= @climbing_route.crag.name %></h3>
  <ul>
    <% @climbing_route.attributes.each do |attr| %>
      <li><%= attr.first %>: <%= attr.last %></li>
    <% end %>
  </ul>
  <%= link_to 'Dashboard', admin_path %>
  <%= link_to 'Edit', admin_edit_climbing_route_path(@climbing_route) %>
</div>